### ISSUE TITLE
Usage with near-operation-file-preset?

### ISSUE THREAD

**Issue by leggomuhgreggo** [ryan-m-walker/graphql-codegen-mock-results#1]
Hello! I was wondering if there's any way to use the plugin with [near-operation-file-preset plugin](https://www.graphql-code-generator.com/plugins/near-operation-file-preset), so that the factories are shaped/co-located with respect to individual .graphql documents.

Thanks!

**Comment by ryan-m-walker** [comment]
Hi, I just tested this out locally and it seems to be working (which is kind of surprising actually since this is the first I'm hearing of that preset haha). Here's an example repo of it working for me. What issues are you facing using it? Let me know and I'll see if I can help some how

https://github.com/ryan-m-walker/graphql-codegen-preset-test

Here are the generated mock objects:
https://github.com/ryan-m-walker/graphql-codegen-preset-test/blob/main/src/test.generated.tsx#L51
https://github.com/ryan-m-walker/graphql-codegen-preset-test/blob/main/src/test.generated.tsx#L51

**Comment by leggomuhgreggo** [comment]
Holy smokes! Must have flubbed the config first time around. 

Well this is quite a thrill! Thanks pointin' me in the right direction, and of course for the delightful library.
